input:
  image_directory: /Users/alex/terra-submersa/gps/salvan-wall-20220312/images
  gpx: /Users/alex/terra-submersa/gps/salvan-wall-20220312/input/gpsmap-86i-2022-03-12 12.17.36.gpx

output:
  photo_position_plot: /Users/alex/terra-submersa/gps/salvan-wall-20220312/output/gpsmap-86i/images-positions.jpeg
  track_plot: /Users/alex/terra-submersa/gps/salvan-wall-20220312/output/gpsmap-86i/track-positions.jpeg

